#!/usr/bin/env bash

# ezzsh
# Version information: %%VERSION%%

# installs a basic zsh setup
# written by Armin <netzverweigerer@github> Mon Jan 26 03:28:10 CET 2015
# 

# Released under an Attribution 4.0 International (CC BY 4.0) Creative Commons
# License
# 

# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from the
# use of this software.
# Permission is granted to anyone to use this software for any non-commercial
# purpose.
# 

# Redistribution of this software under the following restrictions:
# 
# 1. The origin of this software must not be misrepresented; you must not claim
#    that you wrote the original software. If you use this software in a
#    product, an acknowledgment in the product documentation is required.
# 
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 
# 3. This notice may not be removed or altered from any redistribution.
# 

script="$(readlink -f $0)"
scriptpath=`dirname "$script"`

echo "[ezzsh] Automatic zsh install script - [http://www.zsh.org/]"
echo "[ezzsh] Author: [netzverweigerer@github]"

# change to home directory
cd ~

# look for already present zsh config
echo "[ezzsh] Looking for existing zsh config..."
if [ -e ~/.zshrc ]; then
  echo ".zshrc exists, creating backup file .zshrc.pre-ezzsh"
  rm -rf ~/.zshrc.pre-ezzsh
  mv ~/.zshrc ~/.zshrc.pre-ezzsh
fi
if [ -e ~/.zsh ]; then
  echo ".zsh exists, creating backup directory .zsh.pre-ezzsh"
  rm -rf ~/.zsh.pre-ezzsh
  mv ~/.zsh ~/.zsh.pre-ezzsh
fi

echo "Cloning forked oh-my-zsh to ~/.zsh ..."
git clone https://github.com/netzverweigerer/oh-my-zsh.git ~/.zsh || exit 1
ln -s ~/.zsh/zshrc ~/.zshrc || exit 1

# mv $HOME/.zsh/oh-my-zsh.sh $HOME/.zsh/zsh
cp ${scriptpath}/theme $HOME/.zsh/themes/ezzsh.zsh-theme
cp $scriptpath/dircolors $HOME/.zsh/

shell="$(getent passwd | grep ^$(whoami) | cut -d":" -f 7)"

if [[ $shell =~ .*/zsh ]]; then
  echo "[ezzsh] login shell: $shell"
else
  echo "[ezzsh] changing shell to zsh..."
  chsh -s "/usr/bin/zsh"
fi

echo "[ezzsh] Performing configuration changes for vim ..."

if [[ -e $HOME/.vim ]]; then
  echo "backing up .vim: "
  mv "$HOME/.vim" "$HOME/.vim.pre.ezzsh"
fi

if [[ -e $HOME/.vimrc ]]; then
  echo "backing up .vimrc: "
  mv "$HOME/.vimrc" "$HOME/.vimrc.pre.ezzsh"
fi

git clone https://github.com/netzverweigerer/.vim.git /tmp/dot-vim.git
mv /tmp/dot-vim.git $HOME/.vim
ln -s $HOME/.vim/vimrc $HOME/.vimrc

git clone https://github.com/powerline/powerline.git /tmp/powerline.git
rm -rf $HOME/git/powerline
mv -vi /tmp/powerline.git $HOME/git/powerline

if [[ -e $HOME/.screenrc ]]; then
  echo "backing up .screenrc: "
  mv "$HOME/.screenrc" "$HOME/.screenrc.pre.ezzsh"
fi

wget -o $HOME/.screenrc https://raw.githubusercontent.com/netzverweigerer/screenrc/master/.screenrc


echo "[ezzsh] ezzsh installation complete. Use the chsh utility to change your"
echo "[ezzsh] shell to zsh. Have a nice day."




# rm "$HOME"/.zsh/README.textile



