#!/bin/sh

# ezzsh
# Version information: %%VERSION%%

# installs a basic zsh setup
# written by Armin <netzverweigerer@github> Mon Jan 26 03:28:10 CET 2015
# 

# Released under an Attribution 4.0 International (CC BY 4.0) Creative Commons
# License
# 

# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from the
# use of this software.
# Permission is granted to anyone to use this software for any non-commercial
# purpose.
# 

# Redistribution of this software under the following restrictions:
# 
# 1. The origin of this software must not be misrepresented; you must not claim
#    that you wrote the original software. If you use this software in a
#    product, an acknowledgment in the product documentation is required.
# 
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 
# 3. This notice may not be removed or altered from any redistribution.
# 


echo "[zsh] Automatic zsh install script - [http://www.zsh.org/]"
echo "[zsh] Author: [netzverweigerer@github]"


# look for already present zsh config
echo "[zsh] Looking for existing zsh config..."
if [ -f ~/.zshrc ]; then
  echo ".zshrc exists, exiting gracefully."
  exit 1
fi
if [ -f ~/.zsh ]; then
  echo ".zsh exists, exiting gracefully."
  exit 1
fi

# get zsh configuration files from github
echo "Cloning git://github.com/sjl/oh-my-zsh.git to ~/.zsh ..."
git clone git://github.com/sjl/oh-my-zsh.git ~/.zsh

# create default zshrc from template
echo "[zsh] Creating default zshrc file from ~/.zsh/templates/zshrc.zsh-template ..."
cp -vi ~/.zsh/templates/zshrc.zsh-template ~/.zshrc

# goodbye
echo "[zsh] Note: use \"chsh\" utility and change your default shell to \"zsh\"."
echo "[zsh] installation successful."

cat ~/.zshrc | sed -iE 's/^ZSH=.*$/ZSH=.zsh/' | grep -v ^source > .zshrc.tmp
echo "source $ZSH/zsh" >> .zshrc.tmp
mv -vi .zshrc.tmp .zshrc

info "changing shell to zsh..."
chsh -s "/usr/bin/zsh"


